### ISSUE TITLE
rubrik_vsphere_live_mount missing?

### ISSUE THREAD

**Issue by davehailwood123** [rubrikinc/rubrik-modules-for-ansible#72]
**Expected Behavior**

Playbook using rubrik_vsphere_live_mount to work

**Current Behavior**

When running a playbook using  rubrik_vsphere_live_mount you get the error:

ERROR! couldn't resolve module/action 'rubrik_vsphere_live_mount'. This often indicates a misspelling, missing collection, or incorrect module path.

**Steps to Reproduce**

1. Follow Quick Start Guide or use Ansible Galaxy to download cdm collection
2. Write playbook to use rubrik_vsphere_live_mount
3. Run Playbook

```
    - name: LiveMount vSphere VM
      rubrik_vsphere_live_mount:
        provider: "{{credentials}}"
        vm_name: "{{ snapshot_name }}"
        date: "latest"
        time: "latest"
        host: "{{ VSphereHost }}"
        remove_network_devices: "True"
```

**Context**
I'm trying to use the live mount modules as part of a workflow to create dev/test environments from our backups. Modules that have been added recently to the documentation are missing from the default branch on github. I've tried using the module-merge branch but this also fails. Are the new modules ready to be used?
