### ISSUE TITLE
On-demand snapshot fails when trying to match a host pattern or limiting to a specific inventory group

### ISSUE THREAD

**Issue by ramateja3** [rubrikinc/rubrik-modules-for-ansible#80]
**Expected Behavior**
I'm trying to take an On Demand snapshot in Rubrik using 'rubrik_on_demand_snapshot' module.  I wanted to match a host pattern or use an inventory group for each specific rubrik cluster. 

For example: If the VM name is part of 'IAD' inventory group, I wanted to use 'IAD' Rubrik cluster, and if the VM is part of 'MIL', backup should be taken on MIL Cluster.  

**Current Behavior**

Conditional check is not happening, if  i use either of the below: 
when: inventory_hostname in groups['IAD'] 
when: "'usva' in {{ vm_name }} "

Playbook fails with below error:

fatal: [localhost]: FAILED! => {"msg": "The conditional check 'inventory_hostname in groups['MIL']' failed. The error was: error while evaluating conditional (inventory_hostname in groups['MIL']): Unable to look up a name or access an attribute in template string ({% if inventory_hostname in groups['MIL'] %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'AnsibleUndefined' is not iterable\n\nThe error appears to be in '/root/rubrik/rubrik-modules-for-ansible/roles/rubrik/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# tasks file for rubrik\n- name: Take an On demand Snapshot for  VM\n  ^ here\n"}

**Failure Information (for bugs)**

* Use verbose outputs to capture any debug information.
```
---
# tasks file for rubrik
- name: Take an On demand Snapshot for  VM
  rubrik_on_demand_snapshot:
    object_name: "{{ item }}"
    provider: "{{ iadcredentials }}"
    timeout: 60
  with_items:
    - "{{ inventory_hostname }}"
  when: inventory_hostname in groups['IAD']
  rubrik_on_demand_snapshot:
    object_name: "{{ item }}"
    provider: "{{ 601credentials }}"
    timeout: 60
  with_items:
    - "{{ inventory_hostname }}"
  when: inventory_hostname in groups['MIL']

```

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

Use a when condition for on demand snapshot module and it's reproducible. 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

I'm using Ansible version 2.9.2. Please help in correcting if i m wrong. 

Ansible.cfg:

[defaults]
inventory=/root/rubrik/inventory
library = ./rubrikinc/cdm/plugins/modules
module_utils   = ./rubrikinc/cdm/plugins/module_utils
roles_path = /root/rubrik/rubrik-modules-for-ansible/roles
