### ISSUE TITLE
certificate timeout with rubrik_physical_host module

### ISSUE THREAD

**Issue by watsonb** [rubrikinc/rubrik-modules-for-ansible#81]
**Expected Behavior**

Expect that I can add a Windows host to the Rubrik cluster by IP address

**Current Behavior**

I'm currently getting an error message:

`Timed out while getting certificate at <ip>:12801`

**Failure Information (for bugs)**

I'm using your rubrik_* modules as part of my custom Rubrik Ansible role that installs the agent onto freshly built virtual machines.  My role used to do just that, download and install the agent.  Now that I've discovered these provided modules, I'm also doing things like setting up VMWare snaps via an SLA, supporting Filesets, and SQL backups.

My role supports VMWare machines as well as Linux and Windows hosts.  The VMWare stuff works for both Windows and Linux without issue.  The Fileset is currently working for Linux, but not for my Windows test case via `molecule`.  Under normal circumstances, all freshly built hosts would be part of a Windows domain and therefore have names/objects in Active Directory and be resolvable.  For my `molecule` testing, I simply feed the IP addresses of hosts to the `rubrik_physical_host` module's `hostname` attribute, as these machines are "fleeting" and not part of any domain/AD object.  As I mentioned, this works for my Linux test cases (Ubuntu, RedHat, CentOS, etc.) but not for Windows (Server 2016).

* Use verbose outputs to capture any debug information.
```
The full traceback is:
    WARNING: The below traceback may *not* be related to the actual failure.
      File "/tmp/ansible_rubrik_physical_host_payload_npytTE/__main__.py", line 136, in main
        api_request = rubrik.add_physical_host(ansible["hostname"], ansible["timeout"])
      File "/home/ben/venv_ansible-2.8.5/local/lib/python2.7/site-packages/rubrik_cdm/physical.py", line 90, in add_physical_host
        return self.post('v1', '/host', config, timeout)
      File "/home/ben/venv_ansible-2.8.5/local/lib/python2.7/site-packages/rubrik_cdm/api.py", line 214, in post
        authentication=authentication)
      File "/home/ben/venv_ansible-2.8.5/local/lib/python2.7/site-packages/rubrik_cdm/api.py", line 143, in _common_api
        raise APICallException(error_message)
    
    fatal: [knemol-ar-rubrik-windows-benlocal -> localhost]: FAILED! => {
        "changed": false, 
        "invocation": {
            "module_args": {
                "action": "add", 
                "api_token": null, 
                "hostname": "<WINDOWS_HOST_IPV4_ADDRESS>", 
                "node_ip": "rubrik.example.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "provider": {
                    "api_token": null, 
                    "node_ip": "rubrik.example.com", 
                    "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                    "username": "my_admin_user"
                }, 
                "timeout": 240, 
                "username": "my_admin_user"
            }
        }, 
        "msg": "Timed out while getting certificate at <WINDOWS_HOST_IPV4_ADDRESS>:12801"
```

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

* Create fresh Windows VM
* Install Rubrik agent, verify service running
* Note Windows host IP address
* Execute `rubrik_physical_host` Ansible task

```yaml
- name: RUBRIK_PHYSICAL_HOST | add host to Rubrik cluster
  delegate_to: localhost
  rubrik_physical_host:
    provider: "{{ credentials }}"
    action: add
    hostname: "{{ fileset_item.hostname | default( rubrik_host_ip_addr ) }}"
    timeout: "{{ fileset_item.timeout | default(omit) }}"
```

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* rubrik-modules-for-ansible (devel branch (commit 361a29...c25a98) Feb 11th)
* rubrik-cdm install via `pip`, version 2.0.6
* Ansible OS -> Ubuntu 18.04 LTS
* Ansible version 2.8.5
* Host OS being added by IP -> Windows Server 2016 Datacenter Edition

**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.

```
Paste into a code block.
```

**Comment by watsonb** [comment]
I reviewed my role a bit more and ensured Windows firewall ports 12800 and 12801 were open and now I'm getting this error message when trying to add the host to Rubrik cluster:

`Timed out while getting agent info at <ip>:12800`

**Comment by drew-russell** [comment]
@watsonb both of those error messages are Rubrik centric (i.e. not related to Ansible or the API).

Can you open a ticket with Support (probably can just forward this chain to support@rubrik.com) and we can dig into it deeper there

**Comment by watsonb** [comment]
I'm getting a little deeper into this.  I suspect it has something to do with how the service is running (or not) on my Windows box.  Specifically regarding the account the service is running as and the "log on as a service" user right.  I'm making tweaks and will report back for posterity.

**Comment by watsonb** [comment]
I've sent an e-mail to Support.  In the meantime, I figure I'd update this issue with some of the Ansible tasks I've used to get me to the point I'm at.  When I create the new machines via `molecule`, I have the following preparatory tasks that create a user account that will run Rubrik service/agent:

```yaml
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:

    - name: create test windows user
      win_user:
        name: foobar
        password: mysecretpassword
        description: "test user for role"
        fullname: "Foo Bar"
        state: present
        password_never_expires: true
        user_cannot_change_password: true
        update_password: on_create
        groups:
          - Users
          - Administrators

    - name: ensure test user has Log on as a service right
      win_user_right:
        name: SeServiceLogonRight
        users:
        - .\foobar
        action: add
```

And here are my Windows tasks for installing the agent and handling firewall rules

```yaml
---
- name: WIN_FILE | (Windows) Create a Temporary Download Location
  win_file:
    path: C:\Temp
    state: directory

- name: WIN_GET_URL | (Windows) Download the Rubrik Connector
  win_get_url:
    url: "https://{{ rubrik_cluster_ip }}/connector/RubrikBackupService.zip"
    dest: C:\Temp\RubrikBackupService.zip
    validate_certs: false
    force: false

- name: WIN_UNZIP | (Windows) Unzip the Connector Archive
  win_unzip:
    src: C:\Temp\RubrikBackupService.zip
    dest: C:\Temp\
    creates: C:\Temp\RubrikBackupService.msi

- name: WIN_PACKAGE | (Windows) Install the Rubrik Connector
  win_package:
    path: C:\Temp\RubrikBackupService.msi
    state: present
    creates_service: 'Rubrik Backup Service'
    wait: true

- name: WIN_SERVICE | (Windows) Set Logon for the Rubrik Connector Service
  win_service:
    username: "{{ rubrik_service_username }}"
    password: "{{ rubrik_service_password }}"
    name: 'Rubrik Backup Service'


---

- name: WIN_FIREWALL_RULE | Firewall rule to allow Rubrik ports
  win_firewall_rule:
    name: Rubrik
    localport: "{{ item }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  loop:
    - "12800"
    - "12801"
```

I found the agent log location and in the logs I'm seeing this:

```
I0313 08:08:29.910814  1492 BackupAgentMain.cpp:182] Listen on port 12801
I0313 08:08:30.160817  1492 BackupAgentMain.cpp:217] Backup agent thread started.
I0313 08:10:15.256603  3496 AgentUtil.cpp:91] Received request getCertificate with tag HostRegister
I0313 08:10:15.256603  3496 FileHandler.cpp:336] Read 1306 bytes from file C:\ProgramData\Rubrik\Rubrik Backup Service\backup-agent.pub
I0313 08:10:15.256603  3496 AgentUtil.cpp:96] Request getCertificate with tag HostRegister completed successfully.
```
There is a time gap between when the service is started locally (2nd line) and when the playbook executes the rubrik_physical_host task (3rd line).

Is there a way to crank up the logs on the agent side to see any more information.  I'll work with my team that manages the actual Rubrik backup cluster to check for logs there.

**Comment by watsonb** [comment]
OK, I figured out my problem.  It turns out I wasn't opening up the firewall ports (via Ansible) in the correct manner.  I was using a loop to open the ports but the rule name stayed the same.  Hence, every time I would `molecule converge` I would see changed in the firewall task output.  Looking deeper at debugging, it was changing because first it would set the rule to one of the ports, then change it to the other port vice adding rules for both.

My silly mistake.  I've since updated the firewall task as follows:

```yaml
- name: WIN_FIREWALL_RULE | Firewall rule to allow Rubrik ports
  win_firewall_rule:
    name: Rubrik
    localport: 12800-12801
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
```

Rather than looping, this adds both ports as a range.  I think I could have comma-delimited them as well.

Now my `rubrik_physical_host` and subsequent `rubrik_assign_physical_host_fileset` tasks are working as expected.  I'll go ahead and close this issue.
