### ISSUE TITLE
Error while running ansible playbook - The Rubrik Python SDK is required for this module (pip install rubrik_cdm)

### ISSUE THREAD

**Issue by punit-devops** [rubrikinc/rubrik-modules-for-ansible#90]
Hi

I am running my first ansible playbook for rubrik. 
I have already installed python SDK. Below is the output if I run it again.

```
# pip install rubrik_cdm
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Requirement already satisfied: rubrik_cdm in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: requests!=2.22.0,>=2.18.4 in /usr/local/lib/python3.6/site-packages (from rubrik_cdm)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/site-packages (from rubrik_cdm)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from rubrik_cdm)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests!=2.22.0,>=2.18.4->rubrik_cdm)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests!=2.22.0,>=2.18.4->rubrik_cdm)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests!=2.22.0,>=2.18.4->rubrik_cdm)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests!=2.22.0,>=2.18.4->rubrik_cdm)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil->rubrik_cdm)

``` 

Have also cloned the git repo mentioned in quick start guide, using command:
`git clone https://github.com/rubrikinc/rubrik-modules-for-ansible.git`

Still when I run the first test ansible, I get an error i.e. 
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "The Rubrik Python SDK is required for this module (pip install rubrik_cdm)."}
`

Below are the content of my playbook:
```
---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: <NAME>

  tasks:
    - name: On-Demand Snapshot
      rubrikinc.cdm.rubrik_on_demand_snapshot:
        object_name: "{{ vm_name }}"

```
Please help me fixing the error.
